server:
  port: 8085

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR

spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

jwt:
  secret: ${JWT_SECRET}

admin:
  username: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

gmail:
  secret: ${GMAIL_JSON}